-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.contact_inquiries (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  email text NOT NULL,
  phone text,
  subject text NOT NULL,
  message text NOT NULL,
  status text DEFAULT 'new'::text,
  assigned_to uuid,
  responded_at timestamp with time zone,
  response text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT contact_inquiries_pkey PRIMARY KEY (id),
  CONSTRAINT contact_inquiries_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.profiles(id)
);
CREATE TABLE public.dealer_applications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  business_name text NOT NULL,
  business_type text NOT NULL,
  business_address text NOT NULL,
  city text NOT NULL,
  state text NOT NULL,
  pincode text NOT NULL,
  business_phone text NOT NULL,
  business_email text,
  gst_number text,
  pan_number text,
  aadhar_number text,
  current_business text,
  experience_years integer,
  investment_capacity text,
  preferred_areas ARRAY,
  why_partner text,
  documents jsonb,
  status USER-DEFINED DEFAULT 'pending'::dealer_status,
  reviewed_at timestamp with time zone,
  reviewed_by uuid,
  rejection_reason text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  terms_accepted boolean NOT NULL DEFAULT false,
  terms_accepted_at timestamp with time zone,
  CONSTRAINT dealer_applications_pkey PRIMARY KEY (id),
  CONSTRAINT dealer_applications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT dealer_applications_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.dealers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  business_name text NOT NULL,
  business_address text NOT NULL,
  business_phone text NOT NULL,
  business_email text,
  gst_number text,
  pan_number text,
  city text NOT NULL,
  state text NOT NULL,
  pincode text NOT NULL,
  latitude numeric,
  longitude numeric,
  status USER-DEFINED DEFAULT 'pending'::dealer_status,
  commission_rate numeric DEFAULT 10.00,
  documents jsonb,
  approved_at timestamp with time zone,
  approved_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dealers_pkey PRIMARY KEY (id),
  CONSTRAINT dealers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT dealers_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.leads (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  email text NOT NULL,
  phone text NOT NULL,
  city text,
  state text,
  vehicle_interested uuid,
  source text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  status USER-DEFINED DEFAULT 'new'::lead_status,
  assigned_to uuid,
  dealer_id uuid,
  notes text,
  contacted_at timestamp with time zone,
  qualified_at timestamp with time zone,
  converted_at timestamp with time zone,
  lost_reason text,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT leads_pkey PRIMARY KEY (id),
  CONSTRAINT leads_dealer_id_fkey FOREIGN KEY (dealer_id) REFERENCES public.dealers(id),
  CONSTRAINT leads_vehicle_interested_fkey FOREIGN KEY (vehicle_interested) REFERENCES public.vehicles(id),
  CONSTRAINT leads_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.profiles(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  type text NOT NULL,
  priority text DEFAULT 'normal'::text,
  read boolean DEFAULT false,
  read_at timestamp with time zone,
  data jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.orders (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  order_number text NOT NULL DEFAULT generate_order_number() UNIQUE,
  user_id uuid,
  dealer_id uuid,
  vehicle_id uuid,
  quantity integer NOT NULL DEFAULT 1,
  unit_price numeric NOT NULL,
  total_amount numeric NOT NULL,
  tax_amount numeric DEFAULT 0,
  discount_amount numeric DEFAULT 0,
  final_amount numeric NOT NULL,
  status USER-DEFINED DEFAULT 'pending'::order_status,
  payment_method USER-DEFINED,
  payment_status USER-DEFINED DEFAULT 'pending'::payment_status,
  shipping_address jsonb NOT NULL,
  billing_address jsonb,
  notes text,
  metadata jsonb,
  confirmed_at timestamp with time zone,
  shipped_at timestamp with time zone,
  delivered_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  cancellation_reason text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT orders_dealer_id_fkey FOREIGN KEY (dealer_id) REFERENCES public.dealers(id),
  CONSTRAINT orders_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  order_id uuid NOT NULL,
  user_id uuid,
  amount numeric NOT NULL,
  currency text DEFAULT 'INR'::text,
  status USER-DEFINED DEFAULT 'pending'::payment_status,
  method USER-DEFINED NOT NULL,
  razorpay_order_id text,
  razorpay_payment_id text,
  razorpay_signature text,
  razorpay_response jsonb,
  failure_reason text,
  refund_amount numeric,
  refund_status text,
  refund_id text,
  refunded_at timestamp with time zone,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT payments_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text NOT NULL UNIQUE,
  name text,
  phone text,
  role USER-DEFINED DEFAULT 'customer'::user_role,
  avatar_url text,
  address text,
  city text,
  state text,
  pincode text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.test_rides (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  dealer_id uuid,
  vehicle_id uuid,
  name text NOT NULL,
  email text NOT NULL,
  phone text NOT NULL,
  preferred_date date NOT NULL,
  preferred_time time without time zone NOT NULL,
  alternate_date date,
  alternate_time time without time zone,
  city text NOT NULL,
  address text,
  status USER-DEFINED DEFAULT 'pending'::test_ride_status,
  confirmation_code text DEFAULT generate_confirmation_code() UNIQUE,
  notes text,
  dealer_notes text,
  confirmed_date date,
  confirmed_time time without time zone,
  completed_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  cancellation_reason text,
  feedback_rating integer CHECK (feedback_rating >= 1 AND feedback_rating <= 5),
  feedback_comment text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT test_rides_pkey PRIMARY KEY (id),
  CONSTRAINT test_rides_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id),
  CONSTRAINT test_rides_dealer_id_fkey FOREIGN KEY (dealer_id) REFERENCES public.dealers(id),
  CONSTRAINT test_rides_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.vehicles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  type USER-DEFINED NOT NULL,
  brand text NOT NULL,
  model text NOT NULL,
  price numeric NOT NULL,
  discounted_price numeric,
  description text,
  features jsonb,
  specifications jsonb,
  images ARRAY,
  colors ARRAY,
  status USER-DEFINED DEFAULT 'active'::vehicle_status,
  stock_quantity integer DEFAULT 0,
  range_km integer,
  top_speed_kmph integer,
  charging_time_hours numeric,
  battery_capacity text,
  motor_power text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT vehicles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.warranties (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  order_id uuid NOT NULL,
  user_id uuid,
  vehicle_id uuid,
  warranty_code text NOT NULL DEFAULT generate_warranty_code() UNIQUE,
  start_date date NOT NULL,
  end_date date NOT NULL,
  status text DEFAULT 'active'::text,
  terms jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT warranties_pkey PRIMARY KEY (id),
  CONSTRAINT warranties_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT warranties_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id),
  CONSTRAINT warranties_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);